port: 4002
description: "This is the Fieldwork & Professional Practice web site."
url: "http://localhost:4002" # Use your production URL when deploying.
baseurl: "" # Leave empty if your site is at the root domain.
twitter_username: alainparadis
github_username:  alainparadis
collections:
  posts:
    output: true
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
