port: 4002
description: "This is the Fieldwork & Professional Practice web site."
url: "http://localhost:4002"
baseurl: ""
twitter_username: alainparadis
github_username:  alainparadis
collections:
  posts:
    output: true
exclude:
  - .sass-cache/
  - .jekyll-cache/
